version: 1.0.{build}
init:
- ps: Install-Product node 6.2.0
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  OCTOPUS_API:
    secure: +DI+SrzWnbiUUsjEBQKINbCOauwT8+Xm3t0zeIqExlg=
cache:
- src\MailTrace.Site\node_modules
- packages
build_script:
- cmd: "nuget restore\nmsbuild \"MailTrace.sln\" /p:RunOctoPack=true /m /verbosity:minimal /logger:\"C:\\Program Files\\AppVeyor\\BuildAgent\\Appveyor.MSBuildLogger.dll\" \n\ncd src\\MailTrace.Site\n\nnpm version\nnpm install\nnpm run prod"
deploy_script:
- ps: >-
    $url = 'https://download.octopusdeploy.com/octopus-tools/3.3.18/OctopusTools.3.3.18.zip'

    $out = 'OctopusTools.zip'


    (New-Object System.Net.WebClient).DownloadFile($url, $out)


    Expand-Archive $out -DestinationPath .\


    where .\Octo.exe