// <auto-generated />
namespace MailTrace.Data.Postgresql.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class V5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V5));
        
        string IMigrationMetadata.Id
        {
            get { return "201609022315132_V5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
